### ISSUE TITLE
Broken Link in Chapter 4 Overview

### ISSUE THREAD

**Issue by jackrsturm** [TeamBasedInquiryLearning/calculus#1]
On the Chapter 4 overview page (https://teambasedinquirylearning.github.io/calculus/2022/IN.html), the CheckIt link in Readiness Assurance part a is not working properly. 

Here's the link: https://stevenclontz.github.io/cal1-tbil-2021-checkit/#/bank/DF3/1/

**Comment by StevenClontz** [comment]
Thanks - this is now fixed in the 2023 edition at least.
