### ISSUE TITLE
Typo in Activity 5.4.8

### ISSUE THREAD

**Issue by jackrsturm** [TeamBasedInquiryLearning/calculus#10]
I think there might be a typo in Activity 5.4.8. It seems that we should choose B. x=sin(theta). That makes dx = 3cos(theta)dtheta. Once we make the substitution, they just have cos(theta)dtheta. I think we lost the 3 that goes with it.

**Comment by StevenClontz** [comment]
This section was refactored and this activity is no longer there in the next edition: https://teambasedinquirylearning.github.io/calculus/2023/TI4.html
