### ISSUE TITLE
Sage pictures not displaying?

### ISSUE THREAD

**Issue by fragandi** [TeamBasedInquiryLearning/calculus#111]
@StevenClontz I assume that in the Calculus book we want sage pictures to just display, not have a sage code cell appear and then have to **evaluate** the code to display the picture. If this is a choice that was made, it might impact several users so I think for the not development version to just have generated images.

Example: https://teambasedinquirylearning.github.io/calculus/2023/AI3.html

**Comment by fragandi** [comment]
@daverosoff says that on the source "the images there were coded as a <sage><input>…</input></sage>. I thought sage images need to look different, like <sageplot> or something"

**Comment by daverosoff** [comment]
> @daverosoff says that on the source "the images there were coded as a …. I thought sage images need to look different, like or something"

More specifically I wondered if these should perhaps be `<image><sageplot>` instead of `<sage><input>`

**Comment by siwelwerd** [comment]
I ran a quick search, and it appears this is the only place in the book that `<sage>` is used, so I don't think it's intentional.

```
(base) drew@Drews-MBP calculus % grep -n "<sage>" source/*/*.ptx
source/06-AI/03.ptx:21:                <sage>
source/06-AI/03.ptx:50:                <sage>
source/06-AI/03.ptx:72:                <sage>
source/06-AI/03.ptx:86:                <sage>
source/06-AI/03.ptx:120:                <sage>
source/06-AI/03.ptx:154:                <sage>
source/06-AI/03.ptx:189:                <sage>
```

**Comment by StevenClontz** [comment]
This is my fault - I forget the rationale at the time. But in fall 2023 there's no reason to do this anyway: it should be a `<sageplot>` and I'll make the change.

**Comment by StevenClontz** [comment]
Oh I think the rationale was "if I create the images like this then the book can be built without having SageMath installed", which is not an issue in the Year of our Lord 2023 thanks to Codespaces.

**Comment by StevenClontz** [comment]
This is turning out to be tricky, see https://groups.google.com/g/pretext-support/c/FF8Xv-5GSIA

Not sure where in the pipeline the bug is - probably we should make the images simpler here so they all build, and seperately I should try to fix the bug.
