### ISSUE TITLE
CheckIt PS2 divide by zero error

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/calculus#114]
Some of the CheckIt PS2 Domain of Power Series problems have denominator $n!$ with summation beginning at $n=0$. But others just have denominator $n$, also starting at $n=0$. See, for example, https://teambasedinquirylearning.github.io/calculus/2023/exercises/#/bank/PS2/2/ . This doesn't appear currently fixed in 2024 edition either, e.g. https://teambasedinquirylearning.github.io/calculus/2024/exercises/#/bank/PS2/3/ We should change denominators to generate $n+1$ instead, or change index.

**Comment by siwelwerd** [comment]
Changing to $n+1$ in that case is a one line change here:
https://github.com/TeamBasedInquiryLearning/calculus/blob/c5c16e7015414cfb5cd3ed4081f47191648378f8/exercises/outcomes/PS/PS2/generator.sage#L30C20-L30C20

Pedagogically, I wonder if changing index would be better, which would be a slightly bigger (and post-coffee) change code-wise, as all of the series are hardcoded in the template to start at 0 right now.
