### ISSUE TITLE
Inconsistencies in CheckIt problems

### ISSUE THREAD

**Issue by sweezyio** [TeamBasedInquiryLearning/calculus#13]
Currently there are inconsistencies between some of the CheckIt problems. In some of the outcomes, it lists the individual problems as "parts" and in others it lists them as "tasks". For example, the problems in DF4 are numbered "Task 1", "Task 2", and "Task 3", however in DF5 the problems are numbered "**Part** 1", "**Part** 2", "**Part** 3", and "**Part** 4". 

For the sake of consistency, I feel that the language should be the same throughout all of the CheckIt problems. (Unless of course there is some reason to have them labeled differently that I just haven't noticed.)

**Comment by StevenClontz** [comment]
Reason for this issue:

https://github.com/TeamBasedInquiryLearning/calculus/blob/main/exercises/outcomes/DF/DF4/template.xml#L2

note the `mode="exercise"`

https://github.com/TeamBasedInquiryLearning/calculus/blob/main/exercises/outcomes/DF/DF5/template.xml#L2

note the `mode="0.2"` error

Basically, https://spatext.clontz.org/ infers that the subdivisions of an exercise-mode knowl should be labeled as tasks, but the default mode knowl splits them into parts. I'll fix this now.
