### ISSUE TITLE
DF1 and DF2 links switched

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/calculus#17]
The link https://teambasedinquirylearning.github.io/calculus/2023/DF1.html actually directs to section DF2. Likewise, the link https://teambasedinquirylearning.github.io/calculus/2023/DF2.html actually directs to section DF1. Not sure how the swap happened, but URLs should be swapped.

**Comment by siwelwerd** [comment]
Looks like these were probably re-ordered, but the xml:ids were not changed.  See

https://github.com/TeamBasedInquiryLearning/calculus/blob/4848d931c491a0921436fa91065de1b5e7a016da/source/02-DF/01.ptx#L3

https://github.com/TeamBasedInquiryLearning/calculus/blob/4848d931c491a0921436fa91065de1b5e7a016da/source/02-DF/02.ptx#L3

I *think* just fixing those two lines will work, but I am not 100% sure at how PreTeXt decides on those URLs -- @StevenClontz probably knows.

**Comment by StevenClontz** [comment]
This is fixed in 555517074716eacfd3139d9a60952d213cc98ab3 and thus in the 2023 (full) Edition. I did not retcon the Early Edition because I don't want to break any existing hyperlinks that instructors may be using.
