### ISSUE TITLE
Activity 2.2.13 answers need correcting

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/calculus#18]
[Activity 2.2.13](https://teambasedinquirylearning.github.io/calculus/2023/DF1.html#second-der-easy) 
https://teambasedinquirylearning.github.io/calculus/2023/DF1.html#second-der-easy

The correct answer here should be f''(x)=-2, but it isn't one of the choices. Perhaps all the possible answers should start with f'' instead of f'.

**Comment by StevenClontz** [comment]
Fixed in [45d54fe](https://github.com/TeamBasedInquiryLearning/calculus/commit/45d54fefb140c929db1c33b981c705045c22c123) for next release
