### ISSUE TITLE
Missing <p> tag on TI8 exercise

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/calculus#2]
Jordan Kostiuk pointed out that the tasks are not showing the integral; a quick inspection shows that this is due to missing `<p>` tags.

https://github.com/TeamBasedInquiryLearning/calculus/blob/fef2afb8d10dbb69258fe8442a6911e3acba6321/exercises/outcomes/TI/TI8/template.xml#L10
https://github.com/TeamBasedInquiryLearning/calculus/blob/fef2afb8d10dbb69258fe8442a6911e3acba6321/exercises/outcomes/TI/TI8/template.xml#L23

**Comment by siwelwerd** [comment]
I guess I don't have the permissions to assign on this repository, so I'll just tag @StevenClontz here to get it fixed in the 2022 version.

**Comment by StevenClontz** [comment]
I think I fixed the organization rules so you have write access to all TeamBasedInquiryLearning projects now.

**Comment by StevenClontz** [comment]
Closed in c5ddfed3294f1c2b58818c009c555197ffb6623e
