### ISSUE TITLE
Consistency fix for Chain Rule

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/calculus#20]
Both the [Product Rule](https://teambasedinquirylearning.github.io/calculus/2023/DF4.html#thm-df-product-rule) and the Quotient Rule are listed as Theorems, with the name of the rule as part of the Theorem. I like this since it makes it easy to copy/paste the links to those rules in other spaces. Meanwhile, the Chain Rule is listed only as [Definition 2.5.5](https://teambasedinquirylearning.github.io/calculus/2023/DF5.html#chain-rule) and the name "Chain Rule" doesn't appear in the heading. For the sake of consistency, I suggest re-labeling the Chain Rule as a Theorem and adding its name to the Theorem heading.

**Comment by StevenClontz** [comment]
![image](https://user-images.githubusercontent.com/1559632/217590165-b9135ff3-492e-4f4c-92a5-82fe5045c041.png)

**Comment by StevenClontz** [comment]
Updated in b99139475d
