### ISSUE TITLE
Question needed at start of Module DF

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/calculus#21]
At the start of each Module the set of [Learning Outcomes](https://teambasedinquirylearning.github.io/calculus/2023/DF.html#objectives-8) begins with a question, but the Module DF question reads "Need a question for this chapter". I suggest _What methods can we use for determining derivatives?_ to align somewhat with the following module's _How can we use derivatives to solve application questions?_ or, alternatively, _How can we determine a function's instantaneous rate of change?_

**Comment by StevenClontz** [comment]
I went with

> How can we measure the instantaneous rate of change of a function?

![image](https://user-images.githubusercontent.com/1559632/218515672-e2bf85f8-2b02-46a5-b2cc-7feb89ef35c7.png)

**Comment by StevenClontz** [comment]
[f198773](https://github.com/TeamBasedInquiryLearning/calculus/commit/f19877335625fc8d3719ff80ccceaed843fb0187)
