### ISSUE TITLE
Blank activity

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/calculus#28]
[Activity 3.5.10](https://teambasedinquirylearning.github.io/calculus/2023/AD5.html#activity-derivativetests-checkit) is missing a function. I nominate` \(f(x)=xe^{x}\)` or anything with an exponential function

**Comment by StevenClontz** [comment]
I fixed the typo that caused the function to be hidden. I stuck with the function that was originally authored; please reopen if you feel strongly that it should be changed to have an exponential function.

**Comment by owensks** [comment]
No that's fine, I couldn't see the hidden function so thought I'd suggest one to save you time of making one yourself, but whatever there is groovy
