### ISSUE TITLE
L'Hôpital's inconsistency

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/calculus#32]
There's some internal inconsistency about the naming of L'Hôpital's Rule. [CheckIt AD9](https://teambasedinquirylearning.github.io/calculus/2023/exercises/#/bank/AD9/1/) problems refer to "L'Hôpital's Rule". The learning outcome at the beginning of section AD9 references [L'Hopital's Rule](https://teambasedinquirylearning.github.io/calculus/2023/AD9.html#li-832), without an s, without an accent. [Theorem 3.9.8: L' Hospital's Rule](https://teambasedinquirylearning.github.io/calculus/2023/AD9.html#theorem-24) has the s, but no accent. [Activity 3.9.11](https://teambasedinquirylearning.github.io/calculus/2023/AD9.html#activity-209) asks us to "try to use l'Hospital's Rule" with a lowercase "l", [Activity 3.9.12](https://teambasedinquirylearning.github.io/calculus/2023/AD9.html#checkit-ad9) writes about "if L'Hopital's Rule may be applied" (uppercase L), and [Activity 3.9.13](https://teambasedinquirylearning.github.io/calculus/2023/AD9.html#lhospital-fail) talks about cases when "L'Hospital's Rule does not help", this time uppercase L and adds the s.

I'm indifferent about which of these we should use, but I feel strongly we should pick one and then stick to it.

**Comment by StevenClontz** [comment]
I agree (both that we need to decide on one convention, and that I don't have a preference on which one we choose).

Can you start this discussion in Slack - I think it'll get a few more eyes there.
