### ISSUE TITLE
CO Section is Missing Videos

### ISSUE THREAD

**Issue by sweezyio** [TeamBasedInquiryLearning/calculus#38]
Throughout the rest of the textbook there are helpful videos at the end of each learning objective, with the exception of the entire CO section. None of the learning objectives have videos embedded at the bottom of the page despite videos existing for those sections within the Calculus 2 playlist on YouTube:

[CO1](https://youtu.be/bXQbmHJw_kY)
[CO2](https://youtu.be/_NwVAjsQNLE)
[CO3](https://youtu.be/uwXQ94qMsRQ)
[CO4](https://youtu.be/KH8n4dihFNU)
[CO5](https://youtu.be/e7A1OeWRtqA)
[CO6](https://youtu.be/zBmgRvJlWtU)

Is there any particular reason why these videos aren't embedded while the rest of the objectives already have their respective videos included?

**Comment by StevenClontz** [comment]
Generally the CO coordinates chapter has several deficiencies, as it wasn't actually taught with by most (all?) our trained TBIL faculty. I should add Tien's videos to the book though.
