### ISSUE TITLE
Clarify +C in 4.3 (and defend with FTC)

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/calculus#4]
[Definition 4.3.1](https://teambasedinquirylearning.github.io/calculus/2022/IN3.html#def-antiderivative) 
https://teambasedinquirylearning.github.io/calculus/2022/IN3.html#def-antiderivative

**Comment by StevenClontz** [comment]
Fixed in 1839bb7bfe49c05616c505340d66ba235b77e07d sort of - still kind of hand-wavy.

**Comment by fragandi** [comment]
I think this issue is obsolete @StevenClontz, I am closing it.
