### ISSUE TITLE
AD6 number 11 CheckIt problem answer wrong

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/calculus#42]
In the answer to Task 1 on AD6 Problem 11, about concavity and inflection points, the answer given in CheckIt seems to have the opposite sign than the true answer. I don't know what's going on, it looks like the second derivative is correct but somehow the signs are off for the intervals given. https://teambasedinquirylearning.github.io/calculus/2023/exercises/#/bank/AD6/11/

**Comment by fragandi** [comment]
Now the CheckIt answer is correct (checked with Desmos https://www.desmos.com/calculator/peys1z9blo ), so I am closing this issue.

**Comment by StevenClontz** [comment]
I'm reopening so @owensks can confirm that her issue is resolved: I don't see any edits to https://github.com/TeamBasedInquiryLearning/calculus/commits/main/exercises/outcomes/AD/AD6 since April 2023 so I'm not sure how this could have been fixed.

**Comment by siwelwerd** [comment]
I believe @owensks may have made a typo in her report; I just checked and Task *2* indeed has an incorrect answer.  So this does still need to be tracked down.

**Comment by siwelwerd** [comment]
Okay, I think the error is here:

https://github.com/TeamBasedInquiryLearning/calculus/blob/494be91917d0855fcdbfe2aff5f4c3296202e898/exercises/outcomes/AD/AD6/generator.sage#L60

Everywhere else, `negatives[0]` is used, so I think `negatives[1]` is a typo.

But really, I am looking up here 

https://github.com/TeamBasedInquiryLearning/calculus/blob/494be91917d0855fcdbfe2aff5f4c3296202e898/exercises/outcomes/AD/AD6/generator.sage#L4-L5

Why do we have an array at all?  Shouldn't this just be `negative=choice([-1,1])`, which would prevent this kind of typo from ever arising?
