### ISSUE TITLE
Issues in TI8 Improper Integrals

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/calculus#58]
[Activity 5.8.7(a)](https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#task-579) 
https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#task-579 needs an equals sign

[Activity 5.8.8(a)](https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#task-582) 
https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#task-582 should ask what happens as b approaches infinity (not a)

[Activity 5.8.6(a)](https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#task-577) 
https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#task-577 should ask what happens as a approaches 0 from the right (not b). Maybe this should be 0^+

[Paragraph](https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#p-2011) 
https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#p-2011 I don't know where the lower limit c came from, I think perhaps it should be lower limit a

[Fact 5.8.4](https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#fact-TI8prule) 
https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#fact-TI8prule
I think this Fact would be easier to understand in this section if we used the term "converges", like "integral converges iff (blah)" instead of "is defined". Something like, given that p is positive, "integral converges if p<1 and diverges for p>=1"

[Activity 5.8.15](https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#activity-356) 
https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#activity-356 says "coverges" not converges

**Comment by siwelwerd** [comment]
The graph in [Activity 5.8.22](https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#activity-TI8zerounbounded) 
 should probably be rescaled down a bit

**Comment by siwelwerd** [comment]
Also [Activity 5.8.21](https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#activity-TI8zerobounded)

**Comment by fragandi** [comment]
Pull request was merged, were all mentioned issues above resolved? In that case this can be closed, otherwise update with issues still pending

**Comment by StevenClontz** [comment]
Looks like that PR only fixed one or two figures.
