### ISSUE TITLE
Typo in Activity 6.1.3

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/calculus#70]
[Activity 6.1.3(a)](https://teambasedinquirylearning.github.io/calculus/2023/AI1.html#task-602) 
https://teambasedinquirylearning.github.io/calculus/2023/AI1.html#task-602 has four integrals listed but none of them starts out with a 12 in front of the x^2 term. I think the 12 should be there, or we should remove it from the problem.

**Comment by StevenClontz** [comment]
Ah I also found this and commented at issue #71 so let's consolidate there.
