### ISSUE TITLE
Another AI1 issue

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/calculus#71]
[Activity 6.1.3(b)](https://teambasedinquirylearning.github.io/calculus/2023/AI1.html#task-603) 
https://teambasedinquirylearning.github.io/calculus/2023/AI1.html#task-603 This answer is wrong, me plus 32 calculus II students just confirmed that we think the answer should be -4

**Comment by StevenClontz** [comment]
It's also missing the `-12` coefficients in the multiple choice leading up to it.

**Comment by StevenClontz** [comment]
And I agree - the average value is not `-12` but `1/3(-12)=-4`.
