### ISSUE TITLE
SQ5 typo Task 829

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/calculus#75]
[Activity 8.5.5(d)](https://teambasedinquirylearning.github.io/calculus/2023/SQ5.html#task-829) has typo "iproper"

**Comment by StevenClontz** [comment]
This is a good chance to practice making a typo fix directly in your web browser, even without a Codespace:

https://github.com/TeamBasedInquiryLearning/calculus/edit/main/source/08-SQ/05.ptx (or navigate to the file directly via https://github.com/TeamBasedInquiryLearning/calculus and click the pencil icon to open the editor)

Fix the typo and then use the green button to make a commit to a "new branch" like `owensks-patch-1`, then open a PR for review.

**Comment by owensks** [comment]
Nice, thanks!

**Comment by StevenClontz** [comment]
Closed by #76
