### ISSUE TITLE
Confusion with Activity 5.4.1

### ISSUE THREAD

**Issue by jackrsturm** [TeamBasedInquiryLearning/calculus#9]
I think that Activity 5.4.1 as it relates to Activities 5.4.2-5.4.4 is confusing for students. In 5.4.1, we have sqrt(1-x^2) over x. But then in the subsequent activities, we lose the "over x" part and just consider the integral of sqrt(1-x^2). My students were confused about where that part went, so I think if it was eliminated from the problem entirely it would be helpful.

**Comment by StevenClontz** [comment]
As mentioned in #8, this was changed to `\sqrt{9-4x^2}` in 2023 edition: https://teambasedinquirylearning.github.io/calculus/2023/TI4.html
