### ISSUE TITLE
SQ3 Irregularities in indexing terms

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/calculus#96]
There are some irregularities in SQ3 with the indexing of partial sums. [Definition 8.3.1](https://teambasedinquirylearning.github.io/calculus/2023/SQ3.html#definition-SQ3partialsumsequence) implies that `A_k` is a partial sum built from adding k-many terms. [Activity 8.3.6](https://teambasedinquirylearning.github.io/calculus/2023/SQ3.html#activity-SQ3simplifyingsum) 
implies that `S_5` is a partial sum built from adding six terms. Maybe it's just Definition 8.3.1 that needs to be changed; I think the rest of the section implies that we index starting at zero, and so `A_k` should always have `(k+1)`-many terms. But [Definition 8.1.2](https://teambasedinquirylearning.github.io/calculus/2023/SQ1.html#definition-34) leads me to think our sequences always are indexed starting at `n=1`. Given the previous two activities, I find I am too confused now to know what to make of [Activity 8.3.3](https://teambasedinquirylearning.github.io/calculus/2023/SQ3.html#activity-SQ3geompartialsum) and where this index should begin.

**Comment by fragandi** [comment]
As you address this issue with SQ3, you might also notice that there is inconsistency between calling a partial sum \(A_k\) vs \(S_k\) which also reappears later in SQ4 where the partial sums are referred to as \(S_k\). Personally, I find the choice of the letter \(S\) more standard, but if one wants to use \(A\) it needs to be more consistent.
